---
title: "HatsForCats.me - Recent Sales"
output: html_document
params: 
  days: 
    label: "# of Recent Days to include"
    value: 7
    min: 0
  product:
    label: "Product to include"
    value: All
    input: select
    choices: [All, Cowboy, Wizard, Santa, Party]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, echo=FALSE, message=FALSE}
productID <- switch(params$product,
                    All = "All",
                    Cowboy = 1,
                    Wizard = 2,
                    Santa = 3,
                    Party = 4)

library(lubridate)
library(dplyr)

# Dynamically compute the given boundaries
end <- Sys.Date()
start <- end - params$days

productStr <- "All products"
if (productID != "All") {
  productStr <- paste0("Product #", productID)
}
rangeStr <- paste0(month(start, label=TRUE), " ", day(start), "-", month(end, label=TRUE), " ", day(end), ", ", productStr)

sales <- readRDS("sales.rds")

if (productID != "All"){
  sales <- sales %>% 
    filter(Product == productID)
}
```

## Sales for `r rangeStr`

Below is the recent sales history for `r rangeStr`. 

```{r, message=FALSE, echo=FALSE}
library(ggplot2)
library(dplyr)
```

```{r, echo=FALSE, warning=FALSE}
lw_sales <- sales %>% 
  filter(Date >= start & Date <= end)

sales_by_day <- lw_sales %>% 
  group_by(Date) %>% 
  tally()
  
ggplot(sales_by_day, aes(Date, n)) + geom_line() + geom_point() + 
  ylim(0, max(sales_by_day$n)) +
  ylab("Total Daily Sales") + ggtitle("Sales Last Week By Day") +
  ggplot2::geom_hline(yintercept = 0)

if (productID == "All") {
  ggplot(lw_sales, aes(Product)) + geom_histogram(stat="count") + xlab("Product ID") + ylab("Sales") + ggtitle("Sales by Product Last Week")
}
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(leaflet)
leaflet(lw_sales) %>% addTiles() %>% addMarkers(
  clusterOptions = markerClusterOptions()
)
```